### ISSUE TITLE
j=julia.Julia()

### ISSUE THREAD

**Issue by jimguymo** [JuliaPy/pyjulia#104]
So I just got to the point where I can import Julia without a problem, but when I try and create the object:
j=julia.Julia()
I get an error saying the system cannot find the file specified.  I am guessing this is a problem with my path, but I am kinda new to this.  Any suggestions?

**Comment by abhi18av** [comment]
Hey I'm having a similar problem.

For me the path problem was solved by adding these to the `.zshrc`

```sh
export Path="/Applications/JuliaPro-0.5.2.1.app/Contents/Resources/julia/Contents/Resources/julia/bin:$PATH"
alias julia="/Applications/JuliaPro-0.5.2.1.app/Contents/Resources/julia/Contents/Resources/julia/bin/julia"
export JULIA_EXE=julia
```

As you can see I'm using the JuliaPro distribution so you might need to link to location of the julia binary.

**Comment by abhi18av** [comment]
Correction - not solved. But that's what I've tried so far...

**Comment by abhi18av** [comment]
So, here's the complete status.

After correction the above noted settings in the `.zshrc` I have now 

```sh
export PATH="$PATH:/Applications/JuliaPro-0.5.2.1.app/Contents/Resources/julia/Contents/Resources/julia/bin"
```

I messed up the Upper case previously :)

**Comment by jimguymo** [comment]
Much obliged!

**Comment by ihnorton** [comment]
Please reopen if necessary.
