### ISSUE TITLE
MethodError when using (indirectly) StaticArrays

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaPy/pyjulia#105]
Since julia version 0.6 I get an error `Julia exception: MethodError` when I try to call a julia module (https://github.com/gher-ulg/divand.jl/) from python. I tried to track the origin of this error and it seems that it is related to the module StaticArrays (which is used indirectly in my module trough the model Roots, requiring ForewardDiff which requires StaticArrays).

Here is the minimal code which reproduces this issue:

The file `TestModule.jl`:

```julia
module TestModule
# this line generates the error, despite StaticArrays are not used
# RuntimeError: Julia exception: MethodError(TestModule.myx2, (Any[1, 2, 3],), 0x0000000000005537)
using StaticArrays
myx2(x)  = x.^2

export myx2
end
```

The file `test_simple_module.py`:

```python
import julia
j = julia.Julia()
# add to directory to TestModule.jl
j.eval('push!(LOAD_PATH,joinpath(ENV["HOME"],"projects/Julia/share"))')
j.using('TestModule')
print j.myx2([1,2,3])
```

I run this example as:

```bash
~/.julia/v0.6/Conda/deps/usr/bin/python2.7 test_simple_module.py
```
The produces the following error:
```
WARNING: redefining constant JULIA_HOME
Traceback (most recent call last):
  File "test_simple_module.py", line 6, in <module>
    print j.myx2([1,2,3])
RuntimeError: Julia exception: MethodError(TestModule.myx2, (Any[1, 2, 3],), 0x0000000000005537)
```

(The python interpreter that comes with my Ubuntu installation produces a Segmentation fault)

One can also reproduce this error by just copying 2 lines from `StaticArrays`:

```julia
module TestModule
# The error above can also be reproduced by just including these two lines from StaticArrays.jl
# from StaticArrays/src/StaticArrays.jl
abstract type StaticArray{S <: Tuple, T, N} <: AbstractArray{T, N} end
# from StaticArrays/src/convert.jl:3
@inline (::Type{SA})(x...) where {SA <: StaticArray} = SA(x)

myx2(x)  = x.^2

export myx2
end
```

In particular it is the conversion operation `(::Type{SA})(x...)` which generates this `MethodError` error.
I am using `pyjulia` current as of today (last update Fri Jun 16 22:59:09 2017, commit  d01b42b).
229 packages depend on `StaticArrays`. It is possible that this issue affect other packages as well.

Any help would be greatly appreciated.

**Comment by TsurHerman** [comment]
This is a world age issue probably(I infer that from the MethodException type) but not sure.

a minimal working example not including StaticArrays
```
import julia

j = julia.Julia()
j.eval("abstract type foo end; (F::Type{bar})(x...) where bar <: foo  = 5")

f= j.eval("f(x) = 2*x")
g=f(2)
```

since eval just calls jl_eval_str ,I guess this is probably a bug in other embeddings of Julia

my personal workaround is to avoid using the jlwrap objects and to just eval everything
this works:
`g = j.eval("f(2)")
`

**Comment by Alexander-Barth** [comment]
Thank you for your comment. However in my case, I have to pass a lot of data. I don't think that I can use `j.eval` here.

I did not know initially what you mean by `world age issue`. It seems hover, that you are referring to issues like these:  https://github.com/JuliaLang/julia/issues/21412
However, I do not see an error message like `The applicable method may be too new: running in world age ...`.

**Comment by TsurHerman** [comment]
I deduce this from this [issue](https://github.com/JuliaPy/PyCall.jl/issues/343)
and from this code running in julia repl:
`f(x) = x;sprint(Base.showerror, MethodError(f, (2,), 0x0000000000005537))`

Please follow up on this thread if you find a proper solution, this is very frustrating.

**Comment by ihnorton** [comment]
Thanks for the minimal reproduction examples to make this easier to understand. I proposed a fix in PyCall:

https://github.com/JuliaPy/PyCall.jl/pull/416
