### ISSUE TITLE
AttributeError: 'Julia' object has no attribute 'gfunction'

### ISSUE THREAD

**Issue by nbecker** [JuliaPy/pyjulia#117]
```#return_array.jl
function f()
    return Array{Complex{Float64}}(1:10)
end

function gfunction(u)
    return sum(u)
end

export f
```

```
In [2]: import julia

In [6]: j = julia.Julia()

In [7]: j.include('return_array.jl')
In [25]: j.f
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-d89de5766ece> in <module>()
----> 1 j.f

AttributeError: 'Julia' object has no attribute 'f'

In [28]: j.gfunction
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-ddb09546f4bb> in <module>()
----> 1 j.gfunction

AttributeError: 'Julia' object has no attribute 'gfunction'
```

I can call using j.eval('f()'), for example, but that's useless - there's no way to pass parameters using eval (except fixed constants that can be put in the string to eval).  Is there any way to make this work?  This is julia 0.6 (python 3.6.2).

**Comment by Keno** [comment]
The python module loader imports a module, so if you wrap it in a module (with `gfunction` exported), and use `j.using("MyModule")`, it'll work fine.

**Comment by stevengj** [comment]
But why shouldn't `include` work?

**Comment by Keno** [comment]
It could, it just doesn't right now. In fact, it probably makes sense to have the `j.foo` syntax resolve the binding `foo` in the Main module rather than doing the ad hoc thing it does right now.

**Comment by tkf** [comment]
I'm closing it since this issue is old and not active.  Please reopen if you still have the issue.

> I can call using j.eval('f()'), for example, but that's useless

You can use `j.eval('f')(x, y, z)`.
