### ISSUE TITLE
Request a pyjulia-feedstock on conda-forge. 

### ISSUE THREAD

**Issue by Carreau** [JuliaPy/pyjulia#126]
And have it provide the pyjulia/julia package.

**Comment by ViralBShah** [comment]
I think this is a great idea. 

cc @StefanKarpinski

**Comment by ViralBShah** [comment]
Maybe we can request help on discourse?

**Comment by Carreau** [comment]
> I think this is a great idea. Would be great to have it be pip installable too.

It is pip installable, you can just `pip install julia`. It just does not pull the Julia interpreter itself :-) I (and Stefan) have the credentials for that. I'm happy to add anyone.

**Comment by ViralBShah** [comment]
Can you add me? Can you outline what needs to be done to pull the julia interpreter? Is it something that we should include in the package itself, or should we have a post-install step that pulls it in? The post-install would be the easiest thing to do, and also would always work.

**Comment by Carreau** [comment]
> Can you add me?

Sure what's your PyPI username ?

> Can you outline what needs to be done to pull the julia interpreter?

I haven't tough of that exactly. 

>  Is it something that we should include in the package itself, or should we have a post-install step that pulls it in? The post-install would be the easiest thing to do, and also would always work.

You could do a post-install but that would limit you to source-distributions (which python is slowly moving away from).


My guess is that most Python+Julia user already have both installed, and thus trying to install julia with pip  at the same time as pyjulia is trying to do the wrong thing. I would leave that to higher package manager (like conda, apt, nix, ...) which can have pyjulia depends both python and julia and can resolve things correctly.

If you go with a Wheel (equivalent of binary distribution for python) then you could precompile you interpreter and just ship it (but then you won't be able to use Julia to install julia packages) and will have issue will linking to all the system libraries.

So I would not try to ship the Julia interpreter with pip. With conda-forge it's a 1 line to add julia as a dependency.

**Comment by ViralBShah** [comment]
I was actually suggesting the post-install script download the julia binary for that platform. Julia's binaries are completely self contained with almost no dependency on system installed libraries. It is self-sufficient and will use everything within its own directory (and can be installed anywhere in the path). It is basically as simple as `wget` and `untar` (or the equivalent on each platform).

**Comment by ViralBShah** [comment]
But, IIUC, you are suggesting not to worry about `pip` providing binaries and let the user get them on their own or through their own package manager. 

For `conda-forge` then, what do we need to do? Just upload an install script somewhere?

My pypi login is ViralBShah.

**Comment by ViralBShah** [comment]
Seems like someone who knows conda-forge can easily download the julia binaries and untar them in the right place. 

https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml

**Comment by ViralBShah** [comment]
For those following along like me, it appears there is already a julia feedstock - https://github.com/conda-forge/julia-feedstock

What we need is a pyjulia feedstock. Sorry @Carreau. Catching up slowly.

**Comment by Carreau** [comment]
> What we need is a pyjulia feedstock. Sorry @Carreau. Catching up slowly.

Haha, no worries. Yes the setting up the feedstock the first time is the hardest. I took me a while to understand how Conda forge works and the nomenclature. Then you just send a PR to a given feedstock, and once it's merge things get build automatically. 

Any conda-forge recipe can depends on any other so we can have `pyjulia-feedstock` depends `julia-feedstock`

Basically you can see that as APT in userspace with environement: each package is a repo on the conda-forge organisation. Every merge on master trigger a build of a new package version.

> I was actually suggesting the post-install script download the julia binary for that platform. Julia's binaries are completely self contained with almost no dependency on system installed libraries. It is self-sufficient and will use everything within its own directory (and can be installed anywhere in the path). It is basically as simple as wget and untar (or the equivalent on each platform).

Yep but Python wheels don't have post-install script, you can do with sdist but it's clunky. But as you discovered if we leave that to conda it should work great. 

(You may want to look at [this long post](https://www.curiousefficiency.org/posts/2016/09/python-packaging-ecosystem.html) which describe in part the role of pip, which is not really a full features package manager but was mostly meant to be used by downstream package manager).

**Comment by Carreau** [comment]
I've submitted https://github.com/conda-forge/staged-recipes/pull/4411 to see if it builds and would get accepted.

**Comment by ChrisRackauckas** [comment]
What caused the PR to be closed? What would it take for this effort to be revived?

**Comment by Carreau** [comment]
I think I never managed to get the recipe to properly build. 
I don't think it's worth to resurect; redoing from scratch will be easier; ecosystem has changed a lot in 2/3 years.

**Comment by MilesCranmer** [comment]
I'm currently trying to get a conda-forge recipe working which has PyJulia as an internal dependency: https://github.com/conda-forge/staged-recipes/pull/17605. The recipe is for my package PySR (which depends on PyJulia) but since there's no PyJulia feedstock in existence I bundled them for simplicity. If it works I think it could be easily split in two.

I'm at the point where I can `import julia` but actually importing `Main` gives this error: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=444567&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=2202
```bash
AttributeError: /home/conda/staged-recipes/build_artifacts/pysr_1642729111742/_build_env/bin/../lib/libjulia.so.1: undefined symbol: jl_
```
If anybody is interested in getting PyJulia working on conda-forge I'd appreciate any insights, thanks.

**Comment by mkitti** [comment]
See https://github.com/JuliaPy/pyjulia/issues/454

**Comment by MilesCranmer** [comment]
https://github.com/conda-forge/staged-recipes/pull/17647 closes this. `pyjulia` now on conda-forge 🥳

**Comment by tkf** [comment]
@MilesCranmer @ngam @mkitti @ocefpaf @isuruf Thanks a lot for solving this :tada:  Bridging the gap between the philosophies on packaging in Julia and Conda is a very tricky task!
