### ISSUE TITLE
Python calling Julia . Many problems 

### ISSUE THREAD

**Issue by mmonterrubio** [JuliaPy/pyjulia#130]
Dear all,
 I want to use a Python code already written  to parallelize my  Julia code. But I have problems using the function that link both languages. I search in the documentations and also in other posts (p.e. http://blog.leahhanson.us/post/julia/julia-calling-python.html ) 
I try to use the git repo
git clone https://github.com/JuliaLang/IJulia.jl
But the python folder is not exist (IJulia.jl/python/)

Then I try to install the pyjulia using pip
sudo pip install julia

but I also have the next error..

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>> import julia
>> j = julia.Julia()
ERROR: UndefVarError: unsafe_string not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/julia/core.py", line 270, in __init__
    """])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['julia', '-e', '\n                println(JULIA_HOME)\n println(Libdl.dlpath(string("lib", splitext(Base.julia_exename())[1])))\n println(unsafe_string(Base.JLOptions().image_file))\n PyCall_depsfile = Pkg.dir("PyCall","deps","deps.jl")\n                 if isfile(PyCall_depsfile)\n eval(Module(:__anon__),\n Expr(:toplevel,\n                        :(using Compat),\n :(Main.Base.include($PyCall_depsfile)),\n :(println(pyprogramname))))\n else\n                    println("nowhere")\n end\n                 ']' returned non-zero exit status 1

Somebody know how to solve this issue?

Best regards,
Marisol

**Comment by clarkevans** [comment]
Marisol, I didn't have such an problem, but I followed the
instructions in the README which ask you to clone and
then use pip to install.

**Comment by tkf** [comment]
I think install instruction is clearer now.
