### ISSUE TITLE
PyCall module not found when called from Python

### ISSUE THREAD

**Issue by cschro** [JuliaPy/pyjulia#131]
Hi guys,

I am freaking out over an error I get when I am trying to run Julia from Python 3.6.3. Somehow the the julia binary is found but it can't seem to find the PyCall module.

`JULIA_HOME = /Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/bin,  libjulia_path = /Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/libjulia.dylib
calling jl_init_with_image(b'/Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/bin', /Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib)
seems to work...
exception occured? None
exception occured? 4683613456
Retrieving exception infos...
libjulia stderr = 4682706352
ArgumentError("Module PyCall not found in current path.\nRun `Pkg.add(\"PyCall\")` to install the PyCall package.")show called ...
Traceback (most recent call last):
  File "run_simulation.py", line 21, in <module>
    main()
  File "run_simulation.py", line 15, in main
    j = julia.Julia(debug=True)
  File "/usr/local/lib/python3.6/site-packages/julia/core.py", line 370, in __init__
    self._call(u"using PyCall")
  File "/usr/local/lib/python3.6/site-packages/julia/core.py", line 412, in _call
    self.check_exception(src)
  File "/usr/local/lib/python3.6/site-packages/julia/core.py", line 432, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:
using PyCall`

The error appears as soon as I call j = julia.Julia(). 

I did everything as mentioned for installation. I added julia to PATH, did Pkg.build("PyCall") and then pip-installed julia. Already deinstalled and re-installed Python3 as well.

Happy for any help!

**Comment by stevengj** [comment]
You maybe installed PyCall in the wrong Julia, if you have multiple versions of Julia installed?  Try explicitly running `/Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/bin/julia`, since that seems to be the Julia version that `pyjulia` wants to use.

**Comment by cschro** [comment]
As far as I know I only have one Julia installed. When running `/Applications/JuliaPro-0.6.0.1.app/Contents/Resources/julia/Contents/Resources/julia/bin/julia` I get to the normal Julia version with `julia> Pkg.installed("PyCall")
v"1.15.0"`.

**Comment by stevengj** [comment]
`Exception 'ArgumentError' occurred while calling julia code: using PyCall` makes it sound like it is finding PyCall but getting an error.

**Comment by cschro** [comment]
Okay so I solved the issue. I completely deinstalled JuliaPro and installed only the command line tool. Now it seems to work.

Do you have knowledge if it is supposed to work with JuliaPro?

Thanks for the help anyway!

**Comment by stevengj** [comment]
@Keno knows more about JuliaPro than me.  Maybe there is something funky about its package paths.
