### ISSUE TITLE
pip install julia?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPy/pyjulia#135]
I have installed pyjulia on a couple machines, but have never gotten
```
pip install pyjulia
```
to work. Instead I found
```
pip install julia
```
to work. Is that the correct command? Should the README be updated to reflect that?

**Comment by Naereen** [comment]
The README *should* be updated! Anyone in the dev team agrees?

I will write the PR as soon as anyone confirm.

**Comment by terasakisatoshi** [comment]
I confirmed `pip install julia` works

**Comment by Naereen** [comment]
OK. I opened the PR, if any dev can merge it #143.

**Comment by Naereen** [comment]
@Keno OK :+1:
