### ISSUE TITLE
Different output's format for similar inputs

### ISSUE THREAD

**Issue by nkrasney** [JuliaPy/pyjulia#142]
I use Python 3.6 and Julia v0.6 on windows 10.
The format of the outputs I get are different even though the inputs are almost the same:

>>>python
>>>import julia
>>>j = julia.Julia()
>>>j.eval("[0.001,1]")
array([ 0.001,  1.   ])
>>>j.eval("[0.001,2]")
array([  1.00000000e-03,   2.00000000e+00])  

Does anyone have an idea why this is so

**Comment by tkf** [comment]
This is just how Numpy works and nothing to do with PyJulia.
