### ISSUE TITLE
Python Calling Julia to use  adding module

### ISSUE THREAD

**Issue by linjianphysics** [JuliaPy/pyjulia#145]
Dear all,
Now I can make it  successfully：
>>> import julia 
>>> j=julia.Julia()
>>> j.sind(90)
1.0
>>> 
But there is a question. I have install a  module into Julia ,and I can see the module in the Pkg.installed(). I can use it via “using ExpmV” in Julia .But now how can I use it in python like j.sind()?

Somebody know how to solve this issue?

Best regards,

Jimmy

**Comment by JobJob** [comment]
```
import julia

j = julia.Julia()

j.using("Distributions")
d1 = j.Categorical([0.1, 0.2, 0.2, 0.3, 0.2])
j.rand(d1)
```

**Comment by tkf** [comment]
It's now:

```python
from julia.Base import rand
from julia.Distributions import Categorical
d1 = Categorical([0.1, 0.2, 0.2, 0.3, 0.2])
rand(d1)
```
