### ISSUE TITLE
Using PyCall from pyjulia fails

### ISSUE THREAD

**Issue by edmundus** [JuliaPy/pyjulia#148]
I am using Julia Version 0.6.2 and Python 2.7.12 on linux.
In Julia, I can execute "using PyCall" without problems.
In Python, importing the julia module works fine, however, when creating the julia object, I get the following error:
`ArgumentError("Module PyCall not found in current path.\nRun `Pkg.add(\"PyCall\")` to install the PyCall package.")Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukas/.local/lib/python2.7/site-packages/julia/core.py", line 370, in __init__
    self._call(u"using PyCall")
  File "/home/lukas/.local/lib/python2.7/site-packages/julia/core.py", line 412, in _call
    self.check_exception(src)
  File "/home/lukas/.local/lib/python2.7/site-packages/julia/core.py", line 432, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:
using PyCall
`
I checked that both use the same Julia bin.

**Comment by jzazo** [comment]
I will describe what I've done to set up pyjulia, please let me know if I have missed something. I know something similar works on Mac, so I don't know why it doesn't work on Ubuntu.

1) Installed Anaconda with python 3.6.5. 
2) Installed JuliaPro 0.6.2.
3) Added JuliaPro installation folder to path in .bashrc.  "julia" is callable from terminal.
4) Added $JUPITER and $PYTHON environment variables to path in in .bashrc. It seems it is using correct libraries.
5) Added PyCall package to julia installation.
6) Cloned pyjulia project. Installed with "pip3 install -e ." within project.
6) Start a python session, type "import julia", which looks OK. After that, "julia.Julia()" outputs "ArgumentError("Module PyCall not found in current path.\nRunPkg.add("PyCall") ..." error from first message.

Why it looks like it cannot find my Julia installation? I've tried to create an alias at /usr/local/bin for julia binary file, but of course it doesn't help. Can anyone help? Thank you.

**Comment by rohanaras** [comment]
I'm having a similar issue as well when I try to `%load_ext julia.magic` in a jupyter notebook.

**Comment by mprogram** [comment]
Adding my vote here too. Will the issue be fixed? I'm having it with Julia 0.7 and wookay/pyjulia/pull/1 adopted patch.

**Comment by tkf** [comment]
It's probably not an issue in PyJulia 0.2.  Please reopen if not.
