### ISSUE TITLE
Pyjulia won't work

### ISSUE THREAD

**Issue by PeterMortensen93** [JuliaPy/pyjulia#153]
I am a totally new to python and Julia, but I need to call julia functions in Python (vOptGeneric, vOptspecific etc.)
I have followed the installationssteps from https://github.com/JuliaPy/pyjulia

But when I go into Python (via Spyder) and try to import julia and call j = julia.Julia(), i get following error:
FileNotFoundError: [WinError 2]

What did I do wrong?

Thank you in advanced.

**Comment by Ellipse0934** [comment]
1) Ensure that all the directors on the previous page have been followed properly.
2) Ensure both Python and Julia's 64-bit version are in use.
3) On windows the PATH variable has Julia and Python.

**Comment by tkf** [comment]
PyJulia 0.2 may give you a better error message.
