### ISSUE TITLE
NoneType variables

### ISSUE THREAD

**Issue by dragonxtek** [JuliaPy/pyjulia#157]
I'm trying to get gurobi.jl output from python, but it can't detect a correct type (maybe string?)
![selection_578](https://user-images.githubusercontent.com/10552658/39153621-104d34ac-4722-11e8-9ebd-2144ef7fa8e4.png)
Maybe exists any way to avoid the gurobi's header? or tell to pyjulia a specific type of data?
How I can access to gurobi's output?

**Comment by stevengj** [comment]
The Julia `include` function returns the value of the last statement in the included file.  If that last statement is something that returns `nothing` (e.g. a print statement), it will be converted to a Python `None` variable (which is of type `NoneType`).

You should edit your `example_gurobi.jl` to put the value you want to return at the end, or simply import and call Gurobi directly from Python via pyjulia.   For help on using Gurobi.jl, you should ask at https://github.com/JuliaOpt/Gurobi.jl or on https://discourse.julialang.org/
