### ISSUE TITLE
Creating julia.Julia() instance crashes python

### ISSUE THREAD

**Issue by ChristianF88** [JuliaPy/pyjulia#165]
C:\Users\Gabi>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j=julia.Julia()

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x4ddcec4 -- PyUnicodeUCS2_DecodeLatin1 at C:\Users\Gabi\.julia\v0.6\Conda\deps\usr\python27.DLL (unknown line)
while loading no file, in expression starting on line 0
PyUnicodeUCS2_DecodeLatin1 at C:\Users\Gabi\.julia\v0.6\Conda\deps\usr\python27.DLL (unknown line)
PyObject_GenericGetAttrWithDict at C:\Users\Gabi\.julia\v0.6\Conda\deps\usr\python27.DLL (unknown line)
PyEval_EvalFrameDefault at C:\Program Files\Python36\python36.dll (unknown line)
PyObject_CallFunctionObjArgs at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalFrameDefault at C:\Program Files\Python36\python36.dll (unknown line)
PyObject_CallFunctionObjArgs at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalFrameDefault at C:\Program Files\Python36\python36.dll (unknown line)
PyObject_CallFunctionObjArgs at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalFrameDefault at C:\Program Files\Python36\python36.dll (unknown line)
Py_CheckFunctionResult at C:\Program Files\Python36\python36.dll (unknown line)
PyFunction_FastCallDict at C:\Program Files\Python36\python36.dll (unknown line)
PyObject_IsInstance at C:\Program Files\Python36\python36.dll (unknown line)
PyType_GenericAlloc at C:\Program Files\Python36\python36.dll (unknown line)
Py_CheckFunctionResult at C:\Program Files\Python36\python36.dll (unknown line)
PyObject_CallFunctionObjArgs at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalFrameDefault at C:\Program Files\Python36\python36.dll (unknown line)
Py_CheckFunctionResult at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalCodeEx at C:\Program Files\Python36\python36.dll (unknown line)
PyEval_EvalCode at C:\Program Files\Python36\python36.dll (unknown line)
PyArena_Free at C:\Program Files\Python36\python36.dll (unknown line)
PyRun_InteractiveOneObject at C:\Program Files\Python36\python36.dll (unknown line)
PyRun_InteractiveLoopFlags at C:\Program Files\Python36\python36.dll (unknown line)
PyRun_AnyFileExFlags at C:\Program Files\Python36\python36.dll (unknown line)
Py_hashtable_size at C:\Program Files\Python36\python36.dll (unknown line)
Py_FatalError at C:\Program Files\Python36\python36.dll (unknown line)
unknown function (ip: 000000001CB4126C)
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 3472341 (Pool: 3470925; Big: 1416); GC: 5

**Comment by jlperla** [comment]
I had pretty much the same error starting from scratch the first time these were installed.

Reproducing was pretty easy:
1. Install `Python 3.6.4 |Anaconda, Inc.| ` on Windows 10.
2. Make sure Julia is in the path.  I am using Julia 0.6.3
3. On Julia  `Pkg.add("PyCall")`  .  For what it is worth,
```
julia> Pkg.installed("PyCall")
v"1.17.0"
```
4. I precompiled in julia with `using PyCall` just to make sure it was loading.
4. in a terminal `pip install julia` 
5. In a `python` interpreter I just followed the example: 
```
import julia
j = julia.Julia()
```
where I the same error as @ChristianF88 at that point.  I notice that it is saying `v0.6\Conda\deps\usr\python27.DLL` in some of the error messages, where we both are using Python 3.  Could that be part of the problem?  Is python 3 actually supported?

**Comment by jlperla** [comment]
Also, I verified that this is happening from the master as well.

**Comment by jlperla** [comment]
@ChristianF88 For me, at least, I tracked down the issue:  You need to build PyCall to point at the same python interpreter you are using to call pyjulia.

I added https://github.com/JuliaPy/pyjulia/pull/169 to make things more clear in the documentation.

**Comment by ChristianF88** [comment]
Thanks a bunch!

**Comment by jugonzal07** [comment]
@jlperla thanks for looking into this issue.

I'm having this issue right now where I can get pyjulia running solely in a python terminal but fails if I try to run a python script. It will fail if I run a python script including:

```
import julia
j = julia.Julia()
```
If I go into terminal and type `python` and run the above line by line, I have no problem. If I were to run this from a script (let's call it `my_julia_script.py`):

`python my_julia_script.py`

I receive the following error:

![image](https://user-images.githubusercontent.com/8460895/43783210-01827986-9a16-11e8-88c7-32931928787c.png)

```  
File "[PATH_TO_MY_PYTHON]\Python\Python35\lib\site-packages\julia\core.py", line 283, in __init__
    self.api = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
  File "[PATH_TO_MY_PYTHON]\Python\Python35\lib\ctypes\__init__.py", line 351, in __init__
```

Here's what I've done:

- `ENV["PYTHON"] = "[PATH_TO_MY_PYTHON]/Python/Python35/python.exe"`
- `Pkg.build("PyCall")` <--from Julia, worked perfectly
- `pip install julia`
- everything run as admin

Any thoughts what this could be?

**Comment by JeremLay** [comment]
@jlperla Thanks for the tip!! I had the same issue and functions perfectly for me now

**Comment by tkf** [comment]
PyJulia 0.2 is out now. So I consider this to be resolved.
