### ISSUE TITLE
Does pyjulia work with Julia 0.7?

### ISSUE THREAD

**Issue by carmagnole** [JuliaPy/pyjulia#177]
Does pyjulia work with Julia 0.7 yet?

I have updated to Julia 0.7, updated $PATH, and reinstalled PyCall and pyjulia respectively in Julia and Python.

I still can't not import Base from julia in ipython.

**Comment by tkf** [comment]
It works in master https://travis-ci.org/JuliaPy/pyjulia/builds/410591111
