### ISSUE TITLE
Using Custom Julia Modules

### ISSUE THREAD

**Issue by chelseas** [JuliaPy/pyjulia#179]
I don't see a mechanism to import and use custom (unregistered) julia modules via pyjulia. E.g. I have written my own julia module in /home/myfiles/my_module.jl  that I can import into julia by extending the LOAD_PATH:
`julia>> push!(LOAD_PATH, "/home/myfiles/my_module.jl")` 
`julia>> using my_module`
but I don't see a way to extend the LOAD_PATH via pyjulia and/or tell pyjulia to look in an additional place for my custom julia module. It is possible that the mechanism exists but I don't see how to use it because I am new to pyjulia. I appreciate any guidance.

**Comment by tkf** [comment]
You can use `julia.Julia.eval` to run any Julia code, like this:

```python
from julia import Julia
jl = Julia()
jl.eval('push!(LOAD_PATH, "/home/myfiles/my_module.jl")')
```
