### ISSUE TITLE
Add documentation about installation and usage of pyjulia

### ISSUE THREAD

**Issue by ufechner7** [JuliaPy/pyjulia#18]
A documentation how to install and how to use pyjulia is missing.
It should be added to Readme.md.

**Comment by souravsingh** [comment]
I think the issue is fixed .Should it be closed?

**Comment by Keno** [comment]
Basic documentation exists in the README, anything further should be a new issue.

**Comment by sondree** [comment]
PyJulia needs further explaination of python version dependencies and required PyCall versions. Relevant issues #57 #51 

Best

**Comment by tkf** [comment]
I think README is clearer now.
