### ISSUE TITLE
How about checking Python version rather than the executable path?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#182]
Currently, pyjulia tries to use separate cache if (1) the path of Python interpreters are different _or_ (2) if the current interpreter is statically linked:

https://github.com/JuliaPy/pyjulia/blob/9dfc132474dcf2d0f7ab4fa1ff06ca8176ec94c7/julia/core.py#L335

But according to @stevengj, all that matter is the major part of the Python version number https://github.com/JuliaPy/pyjulia/pull/172#issuecomment-409357199.  Then isn't it better to just compare the major version number (which is stored in `PyCall/deps/deps.jl`)?  This would alleviate the issue #173 (difficulty of private cache support in Julia >= 0.7) since this makes Python 3 distributed by some Linux distros (but sadly not Ubuntu) usable with the same PyCall cache.  For example, this would make pyjulia usable with Julia >= 0.7 in [python Docker image](https://hub.docker.com/_/python/).

If this is the right way to go, I can do the fix (which would be very straightforward, I think).

**Comment by stevengj** [comment]
Actually, I think I was wrong — [this code](https://github.com/JuliaPy/PyCall.jl/blob/3e5831e45421cdedf16397e3653c308f7b4d68c0/src/startup.jl#L113-L139) will precompile differently if libpython changes (or if libpython is statically linked).

**Comment by tkf** [comment]
Actually, what I meant to write was to replace the check to see if the path is different (`exe_differs`) with check for the major version number.  I wasn't suggesting to remove `determine_if_statically_linked()`.  (Re-reading it, this is totally not obvious --- sorry about that.)

I also just noticed that checking just major version is not enough since this code also would compile differently in Python < 3.2 and Python >= 3.2.  Am I correct?:

https://github.com/JuliaPy/PyCall.jl/blob/3e5831e45421cdedf16397e3653c308f7b4d68c0/src/startup.jl#L108

(Though I think it's OK to drop Python < 3.2.  Aren't they somewhat more exotic than 2.7 nowadays?)

So, does it make sense to replace `exe_differs` with major version check (or major + minor, if we support < 3.2)?

**Comment by tkf** [comment]
Ah, I see. Thanks a lot for the explanation. So then my plan won't work...
