### ISSUE TITLE
AppVeyor stopped working

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#191]
It looks like AppVeyor stopped working between these two commits https://github.com/JuliaPy/pyjulia/compare/e31331a444f757c98a476af0ee311d79dbb75610%5E...8cb559e0e44c57dc9eef3bba5e6c749070ea2c49 although there is no change in appveyor.yml.

Does anybody know what had happened?

@Keno Can you check the dashboard and see if there are some kind of errors?

ref https://github.com/JuliaPy/pyjulia/pull/183#issuecomment-414871699

**Comment by Keno** [comment]
yeah, I reauthorized it.

**Comment by tkf** [comment]
@Keno  Thanks a lot!

It's working now https://ci.appveyor.com/project/Keno/pyjulia/build/1.0.152
