### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by adhal007** [JuliaPy/pyjulia#192]
I tried to follow the procedure for using pyjulia in anaconda distribution and ended up with the following errors.
![screenshot from 2018-08-23 01-18-19](https://user-images.githubusercontent.com/34755237/44513581-97ea5700-a672-11e8-9206-635864c2925c.png)
![screenshot from 2018-08-23 01-19-02](https://user-images.githubusercontent.com/34755237/44513582-97ea5700-a672-11e8-9611-17bc704cd1a5.png)

**Comment by tkf** [comment]
I think installation instruction in README is clear now.
