### ISSUE TITLE
Release PyJulia 0.2?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#198]
Once <strike>#186, #187, #193, and #197</strike> PRs in https://github.com/JuliaPy/pyjulia/milestone/1 are merged (<strike>they are relatively small PRs</strike>; #200 is a bit large), I think it's a good timing to release PyJulia 0.2.  We can then drop Julia 0.6 support right after the release.  What do you think?

@stevengj If you add me as a maintainer I can upload it to PyPI (or maybe you want to do it yourself?).

**Comment by stevengj** [comment]
I'm happy to add you as a maintainer.

**Comment by stevengj** [comment]
@tkf, what is your username on pypi.org?

**Comment by noahstier** [comment]
> this will not be true for lots of people

Whoops, that will still be true. But still, those of us using Debian/Ubuntu/Anaconda, which I assume is a big fraction, are depending on PyJulia + Julia 0.6.

**Comment by tkf** [comment]
0.2 will support 0.6. Dropping support is just a future idea. Nobody is working on it ATM. But it should happen eventually.

I think supporting statically linked Python has to be done in "The Right Way"; i.e., by a proper support from `julia` core https://github.com/JuliaLang/julia/issues/28518.  Until then, I think `python-jl` CLI #200 is a good workaround. Alternatively, Ubuntu/Debian users can also use pyenv: https://github.com/JuliaPy/pyjulia/issues/185#issuecomment-420521153.

**Comment by bstellato** [comment]
Are there any updates on this? The two remaining PRs seem to be ready to merge. 
I am currently using pyjulia master with julia 1.0 and it works pretty well.

**Comment by tkf** [comment]
I actually want to merge a few more patches:
https://github.com/JuliaPy/pyjulia/milestone/1
But I think all of them are ready.

@stevengj Can I merge them and upload it to PyPI?

**Comment by tkf** [comment]
Thanks!

**Comment by tkf** [comment]
So I merged the PRs.  I think I'll upload it soon but you can already try it via:

```
pip install https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=julia
```

I prefer having some feedbacks especially for #200 to see if it really helps.  Though maybe the easiest way to get feedbacks is to just release it :)

**Comment by YP-Ye** [comment]
I have met **UnicodeDecodeError** when I install the new version:
C:\Windows\System32>pip install https://github.com/JuliaPy/pyjulia/archive/maste
r.zip#egg=julia
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Collecting julia from https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=
julia
  Downloading https://github.com/JuliaPy/pyjulia/archive/master.zip
     | 768kB 411kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\YeYipeng\AppData\Local\Temp\pip-install-nh_kdme6\julia\setu
p.py", line 28, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 688: ille
gal multibyte sequence

**Comment by tkf** [comment]
:tada: :tada: :tada: 
https://pypi.org/project/julia/0.2.0/
https://discourse.julialang.org/t/ann-pyjulia-0-2-is-released-with-julia-1-0-support/17227
