### ISSUE TITLE
Add new magic option that loads python variable into julia

### ISSUE THREAD

**Issue by clouds56** [JuliaPy/pyjulia#205]
usage:
```
x, y = 1, 2
```
and in anther shell
```
%%julia --input x,y
println(x+y)
```

**Comment by clouds56** [comment]
That's great!
I didn't know this is implementable.

**Comment by stevengj** [comment]
It's already supported by PyCall in `py"...."` strings, so this would be similar.

**Comment by tkf** [comment]
(I was meant to write this for #262 but I figured here is a better place for this.)

I think we need to write own parer like PyCall does to make it feel really "natural."  For the moment, maybe we can have `--format` (`-f`) option to `%%julia` to use the `str.format` mini-language such that something like the following work

```
%%julia --format
data = {x}    # the data of Python variable x is transferred
code = {x!c}  # x is interpreted as Julia code
str = {x!s}   # x is interpreted as a string literal in Julia
num = {x:.2}  # x is interpreted as a numeric literal in Julia (with given decimal precision)
TT = Tuple{{Any,Any}}  # {} has to be escaped manually
```

This is not as elegant as `$(python code)` but it's good to reuse the concept that Python programmers already know.

I think the custom conversion specifier `c` can be implemented through [`object.__format__`](https://docs.python.org/3/reference/datamodel.html#object.__format__) protocol.  But I haven't checked it yet.

**Comment by tkf** [comment]
Actually, I just remembered that `py"..."` macro already works for doing something similar

```python
In [1]: %load_ext julia.magic
Initializing Julia interpreter. This may take some time...

In [2]: x = 1

In [3]: %%julia
   ...: using PyCall
   ...: py"x + 1"
Out[3]: 2
```
