### ISSUE TITLE
Idea: use PackageCompiler.jl to avoid the precompilation cache nightmare?

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#217]
* Is it possible to use PackageCompiler.jl to create a .so file with libjulia and PyCall?
    - Do we have full runtime? Can we import arbitrary Julia packages?
    - Does it ignore the standard precompilation cache of PyCall?
* Or maybe just create a custom system image with PyCall?

Though we probably still need `fake-julia` for the compilation step.

**Comment by stevengj** [comment]
@lucatrv, any ideas?

**Comment by tkf** [comment]
I looked at PackageCompiler a bit.  I think creating the system image for "Python-mode" is possible if there is an option to pass `julia_cmd` (whose `.exec[1]` would point to `fake-julia/julia` in PyJulia usage).  If @lucatrv et al. are OK with it I think I can make a PR to do that.

Actually, I think more problematic part is (still) the precompilation cache management on the Julia side because the precompilation cache does not change even if you use different system image:

```julia
cache_file_entry(pkg::PkgId) = joinpath(
    "compiled",
    "v$(VERSION.major).$(VERSION.minor)",
    pkg.uuid === nothing ? "$(pkg.name).ji" : joinpath(pkg.name, "$(package_slug(pkg.uuid)).ji")
)

function find_all_in_cache_path(pkg::PkgId)
    paths = String[]
    entry = cache_file_entry(pkg)
    for depot in DEPOT_PATH
        path = joinpath(depot, entry)
        isfile_casesensitive(path) && push!(paths, path)
    end
    return paths
end
```

The function `Base.find_all_in_cache_path` needs to depend on (say) the path of the system image for this plan to work.  I'll suggest it in Julia's issue tracker https://github.com/JuliaLang/julia/issues/27418    It sounds like useful feature to have even for pure-Julia development.

**Comment by lucatrv** [comment]
Also have a look at [PR #26](https://github.com/JuliaLang/PackageCompiler.jl/pull/26) which was attempted time ago but never completed.
