### ISSUE TITLE
Connecting to a running Julia console?

### ISSUE THREAD

**Issue by lthurner** [JuliaPy/pyjulia#224]
Hi,

first of all thanks a lot for improving pyjulia in the last months and now releasing 0.2, great work!
One question about the usage of pyjulia: when starting julia with:

> import julia
> j = julia.Julia()

An instance of julia is started in the background. Is it also possible to connect to an already running instance of Julia that was started in a Julia console or an IDE?

Cheers
Leon

**Comment by tkf** [comment]
> An instance of julia is started in the background.

Just to be clear, what you mean by "an instance" is a Julia _subprocess_, this is not accurate. PyJulia actually loads Julia runtime (`libjulia`) in the same process. So it's not possible to use existing Julia process directly via PyJulia.

(Note that PyJulia does launch Julia program in its initialization process to get some information about Julia installation.  But this Julia process is not used for evaluating Julia code.)

If you just want to execute Python code from existing Julia process, you can just use [PyCall.jl](https://github.com/JuliaPy/PyCall.jl). See also PyCall usage in https://github.com/JuliaPy/pyjulia#troubleshooting

If you want an interactive Python session in an existing Julia REPL, check out https://github.com/tkf/IPython.jl

**Comment by lthurner** [comment]
Thank you for the fast reply! 

> Just to be clear, if what you mean by "an instance" is a Julia subprocess, this is not accurate. PyJulia actually loads Julia runtime (libjulia) in the Python process itself. So it's not possible to use existing Julia process directly via PyJulia.

Thanks for the clarification, I am a complete beginner in Julia.

> If you just want to execute Python code from existing Julia process, you can just use PyCall.jl. See also PyCall usage in https://github.com/JuliaPy/pyjulia#troubleshooting

> If you want an interactive Python session in an existing Julia REPL, check out https://github.com/tkf/IPython.jl

No I do actually want to use Julia from Python, as I am using a Julia package as an optimization engine inside an existing Python library. pyjulia actually works quite well for this, but I wanted to connect to an existing Julia REPL because:

1. The first time I call pyjulia it takes some time to load. This is due to the pyjulia overhead, but also due to the import of the models in Julia (using ...). I thought by connecting to an existing REPL, I would have this load time only once, not every time I start a new python kernel.
2. When executing Julia Code through Python, the console output is not automatically displayed in Python. I thought by connecting to an existing REPL, I could see the Julia-side logging in the Julia console.

I understand now from your answer it is not possible to do this, so I am probably going to have to live with 1. (it's not the end of the world, just a convenience issue). About 2., I looked into how STDOUT can be rerouted to Python, but couldn't quite get it to work. see my comment in #49, maybe you have an idead about this.

**Comment by tkf** [comment]
> pyjulia it takes some time to load

Yeah, that's one of the frustrating point in using Julia. For PyJulia, it's mostly loading time of PyCall. If you feel brave, you can use [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) to make it as fast as loading standard libraries.

Usually, Julia programmers use [Revise.jl](https://github.com/timholy/Revise.jl) to hot-reload packages without re-booting the Julia process.  Maybe you can use similar hot-reload approach for Python packages.  I know IPython has `%autoreload` magic (though I don't know how robust it is). I use a small `importlib.reload` wrapper for this.

> how STDOUT can be rerouted to Python

I already implemented std stream redirection here: https://ipyjulia-hacks.readthedocs.io/en/latest/

It's just that someone (= likely me) has to implement this in PyJulia.
