### ISSUE TITLE
TODO: normalize path case in Windows

### ISSUE THREAD

**Issue by tkf** [JuliaPy/pyjulia#231]
Error found in: https://github.com/JuliaDiffEq/diffeqpy/pull/37

```
E   RuntimeError: It seems your Julia and PyJulia setup are not supported.
E   
E   Julia interpreter:
E       julia
E   Python interpreter and libpython used by PyCall.jl:
E       C:\projects\diffeqpy\.tox\py\scripts\python.exe
E       C:\projects\diffeqpy\.tox\py\scripts\python36.dll
E   Python interpreter used to import PyJulia and its libpython.
E       c:\projects\diffeqpy\.tox\py\scripts\python.exe
E       c:\projects\diffeqpy\.tox\py\scripts\python36.dll
E   
E   In Julia >= 0.7, above two paths to `libpython` have to match exactly
E   in order for PyJulia to work.
```

--- https://ci.appveyor.com/project/ChrisRackauckas/diffeqpy/builds/21168243/job/684yeqmybv84d6o5

Notice uppercase `C:` and lowercase `c:`.

We need to use https://docs.python.org/3/library/os.path.html#os.path.normcase

**Comment by stevengj** [comment]
Should you call  [`samefile`](https://docs.python.org/3/library/os.path.html#os.path.samefile) instead?

**Comment by tkf** [comment]
Yes, that sounds like a better solution. I don't remember why we are not doing this.
