### ISSUE TITLE
pyjulia with a non-default Julia environment

### ISSUE THREAD

**Issue by dingraha** [JuliaPy/pyjulia#242]
From the documentation in the readme, I've figured out how to install pyjulia in a Python virtual environment, and call Julia functions from a Julia package installed in the default julia environment (e.g., `(v1.1)`). How do I configure pyjulia to use packages from a non-default Julia environment that I created with the `activate <foo>` in the Julia Pkg prompt (https://julialang.github.io/Pkg.jl/v1/environments/)?

Thanks!

**Comment by tkf** [comment]
I usually set `JULIA_PROJECT` https://docs.julialang.org/en/latest/manual/environment-variables/#JULIA_PROJECT-1

I think `from julia import Pkg; Pkg.activate(path_to_the_project)` should work, too.

**Comment by dingraha** [comment]
Setting `JULIA_PROJECT` did the trick! Adding that to the Python virtual environment `activate` seems like a good solution. Thanks!
