### ISSUE TITLE
How to convert a list of tuples?

### ISSUE THREAD

**Issue by chengrunyang** [JuliaPy/pyjulia#304]
I have a Julia function that takes an array of tuples as input, e.g., 
```
2-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (1, 2)
```

Now I would like to call this function from Python, thus I would put a list of Python tuples, like `a = [(1, 1), (1, 2)]`, as argument of this Julia function. However, the natural conversion doesn't seem to work if I do
```
import julia
j = julia.Julia()
a = [(1, 1), (1, 2)]
j.fun(a)
```
in Python. Is there a workaround for this conversion? Thanks!

**Comment by tkf** [comment]
It works for me (PyJulia master with Julia 1.1)

```python
In [1]: from julia import Main

In [2]: Main.typeof([(1, 2), (3, 4)])
Out[2]: <PyCall.jlwrap Array{Tuple{Int64,Int64},1}>

In [3]: Main.show([(1, 2), (3, 4)])
Tuple{Int64,Int64}[(1, 2), (3, 4)]
```

It's helpful if you can write down a minimal working example (MWE) to show what you mean by it "doesn't seem to work."  Listing the version of the relevant libraries is also useful, too.

**Comment by chengrunyang** [comment]
I found this is related to a specific function in a Julia package, which makes it not that easy to create a MWE. But I also found a workaround to tackle this, and yes, the direct conversion of a list of tuples has no error.
