### ISSUE TITLE
Custom image missing PyCall when loaded outside of julia-py

### ISSUE THREAD

**Issue by aarmey** [JuliaPy/pyjulia#318]
I've made a custom image using `python3 -m julia.sysimage ckine/sys.so`. Julia loads fine and works when invoked with `julia-py --sysimage ckine/sys.so`. However, if I load it to use within a Python script:

> `from julia.api import LibJulia`
`api = LibJulia.load()`
`api.sysimage = "ckine/sys.so"`
`api.init_julia()`

This invariably failes to find PyCall:

<img width="993" alt="Screen Shot 2019-09-06 at 7 48 24 AM" src="https://user-images.githubusercontent.com/2065146/64437338-f49c9200-d07a-11e9-915c-4c76f4ed0fed.png">

I noticed that `py-julia` invokes `patch.jl` to change where compiled caches are saved. Should this be included when loading Julia within a Python script?

Thanks!

**Comment by tkf** [comment]
What happens if you do `using PyCall` in the REPL started with `julia-py --sysimage ckine/sys.so`?

**Comment by aarmey** [comment]
Huh. I thought it would work, but I get a `ERROR: ArgumentError: Package PyCall not found in current path:`.

**Comment by aarmey** [comment]
Yep, it just seems to be an issue of PyCall missing. If I do `import Pkg; Pkg.add("PyCall")`, everything works via both entry paths. Is it not built into the sysimage?

**Comment by tkf** [comment]
It's built into the system image but I think `using` and `import` first check the environment to see if it is "legal" to import it.  PyJulia probably should use a bit "sneaky" way to import PyCall (bypassing environment check).  Or at least this case should produce a better error message.

**Comment by aarmey** [comment]
Ok, thanks!
