### ISSUE TITLE
"from julia import xxx" requires "julia.call('using XXX')"

### ISSUE THREAD

**Issue by verdimrc** [JuliaPy/pyjulia#39]
This issue has been discussed in Julia user groups (https://groups.google.com/d/msg/julia-users/oAWYShR1Pks/CYV8g2DyGeQJ).

Currently, importing Julia modules needs to be done this way:

``` python
1. import julia
2. j = julia.Julia()
3. j.call("using Clustering")
4. from julia import Clustering
```

Although not overly complicated, it would be convenient if the same could be achieved as:

``` python
1. import julia
2. from julia import Clustering
```

which is just like the original example by Jake Bolewski [here](https://groups.google.com/d/msg/julia-dev/-B90BrkzM6E/dbiRVm5EeRYJ).

**Comment by jingpengwu** [comment]
neither of these two way worked for me.
![image](https://cloud.githubusercontent.com/assets/7651573/22700392/8821e7fc-ed28-11e6-8559-9f325c7e272e.png)

**Comment by jingpengwu** [comment]
Just found that the new syntax is 
```
j.using("ModuleName")
from julia import ModuleName
```

**Comment by rdeits** [comment]
I'm not sure this is working with recent versions of pyjulia:

```
In [1]: import julia; j = julia.Julia()

In [2]: j.using("DataStructures")

In [3]: from julia import DataStructures

In [4]: DataStructures.OrderedDict()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-5350ee7830c7> in <module>()
----> 1 DataStructures.OrderedDict()

TypeError: 'PyCall.jlwrap' object is not callable
``` 

(pyjulia master with Julia v0.5.2)
