### ISSUE TITLE
Julia 1.5-rc2 failure to precompile

### ISSUE THREAD

**Issue by kcajf** [JuliaPy/pyjulia#393]
I have 2 fresh julia installs, 1.4.2 and 1.5-rc2. I've deleted everything in ~/.julia/compiled.

If I alias julia to the 1.4.2 binary and run `julia-py`, and type `using PyCall`, it precompiles fine.
I again `rm -rf ~/.julia/compiled`.
If I alias julia to the 1.5-rc2 binary and run `julia-py`, and type `using PyCall`, I get the following:
```
[ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
ERROR: Failed to precompile PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] to ~/.julia/compiled/v1.5/PyCall/GkzkC_YHXKS.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```
A very unhelpful stacktrace..

Is anyone able to reproduce?

**Comment by tkf** [comment]
I can reproduce this with `PYJULIA_TEST_RUNTIME=julia1.5 CI=true tox -e py37 -- -k test_build_and_load`.

**Comment by tkf** [comment]
It works on CI though...

https://github.com/JuliaPy/pyjulia/pull/353/checks?check_run_id=933833247#step:8:157 (via #353)

**Comment by kcajf** [comment]
That CI shows 1.5.0rc1, not rc2. Do you think that is significant?

**Comment by tkf** [comment]
~1.5.0-rc1 means "1.5.0-rc1 and anything after it but before 1.6". So it currently runs 1.5.0-rc2.

**Comment by kcajf** [comment]
Ah, makes sense. 

In my case, I'm using conda (miniconda), on linux, python 3.7. Not sure if that helps. What platform were you on when you reproduced locally?

**Comment by tkf** [comment]
I'm using Python 3.7 built from the source.  So, I think it's a rather general failure mode.  There are some tweaks in the compile cache generation in `julia` so maybe that's relevant.  But I'm not sure what's going on yet.

**Comment by tkf** [comment]
#394 fixes it for me

**Comment by kcajf** [comment]
Neat - is there an easy way for me to test your branch? Can I pip install it somehow?

**Comment by tkf** [comment]
`python3 -m pip install --user 'https://github.com/tkf/pyjulia/archive/julia_py.zip#egg=julia'` I think?

**Comment by kcajf** [comment]
Thanks! This seems to be getting me past the PyCall precompile error, although unfortunately I'm now once again hitting the original error in https://github.com/JuliaPy/pyjulia/issues/389#issue-656624744, although this time it doesn't fix itself if I remove the precompile cache :(

**Comment by kcajf** [comment]
Actually, it seems that despite not being able to run `using PyCall` in `julia-py`, I can still build a sytem image with it and PackageCompiler. Strange, but not a blocker. Thanks for all your help! It would be great if this fix could be put into a release.

**Comment by tkf** [comment]
Can you use the system image?  If `python3 -m julia.sysimage sys.so` worked it means `PyCall` was loaded at some point. Note also that:

https://github.com/JuliaPy/pyjulia/blob/a43f7a488013e22d371d4da1df8948dcc76ac8e8/src/julia/julia_py.py#L4-L12

**Comment by kcajf** [comment]
It seems like when I actually try to use it, I get the stacktrace again:
```
➜  ~ julia-py --sysimage julia-sysimage-py.so
Error processing line 1 of /data/home/lib/python3.7/site-packages/matplotlib-3.1.3-py3.7-nspkg.pth:

Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/data/home//lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/data/home/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/data/home/lib/python3.7/contextlib.py", line 5, in <module>
    from collections import deque
  File "/data/home/lib/python3.7/collections/__init__.py", line 24, in <module>
    import heapq as _heapq
  File "/data/home/lib/python3.7/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/lib/python3.7/site.py", line 579, in <module>
    main()
  File "/data/home/lib/python3.7/site.py", line 566, in main
    known_paths = addsitepackages(known_paths)
  File "/data/home/lib/python3.7/site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/data/home/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/data/home/lib/python3.7/site.py", line 178, in addpackage
    import traceback
  File "/data/home/lib/python3.7/traceback.py", line 3, in <module>
    import collections
  File "/data/home/lib/python3.7/collections/__init__.py", line 24, in <module>
    import heapq as _heapq
  File "/data/home/lib/python3.7/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module
```

**Comment by tkf** [comment]
Is `julia-py` installed in the environment of the `python` binary you use to build the system image?

For more automated check, you can run

`
PYJULIA_TEST_RUNTIME=PATH/TO/julia1.5 PYJULIA_TEST_REBUILD=yes CI=true PATH/TO/bin/python -m julia.runtests -- -k test_build_and_load -sv
`

**Comment by tkf** [comment]
Actually there was a bug in #394.  I think it's fixed now.

**Comment by kcajf** [comment]
Thanks, I'll test that later today.

**Comment by kcajf** [comment]
I tried doing the same thing after the fix and get something new now:

```
~ julia-py
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0-rc2.0 (2020-07-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PyCall
[ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
┌ Error: Failed to monkey-patch `julia`
│   exception =
│    Evaluation into the closed module `Base` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Base` with `eval` during precompilation - don't do this.
│    Stacktrace:
│     [1] eval at ./boot.jl:331 [inlined]
│     [2] eval(::Module, ::Expr) at ./Base.jl:39
│     [3] top-level scope at /data/home/../lib/python3.7/site-packages/julia/patch.jl:32
│     [4] include(::Function, ::Module, ::String) at ./Base.jl:380
│     [5] include(::Module, ::String) at ./Base.jl:368
│     [6] top-level scope at none:1
│   getpid() = 14274
└ @ Main /data/home/.../lib/python3.7/site-packages/julia/patch.jl:59
julia-py: Error in /data/home/.../lib/python3.7/site-packages/julia/patch.jl
ERROR: Failed to precompile PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] to /home/.../.julia/compiled/v1.5/PyCall/tJuEG_YHXKS.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```

**Comment by tkf** [comment]
`julia-py` is not for direct use:

```console
% julia-py --help
usage: julia-py [--julia JULIA] [--pyjulia-debug] [<julia arguments>...]

Launch Julia through PyJulia.

Currently, `julia-py` is primary used internally for supporting
`julia.sysimage` command line interface. [...]
```

**Comment by kcajf** [comment]
Ah, thanks, I hadn't realised. System image is building OK on 1.5 now!
