### ISSUE TITLE
How to cite PyJulia

### ISSUE THREAD

**Issue by stevengogogo** [JuliaPy/pyjulia#429]
I'm currently using this package for my master thesis. I'd like to know how to cite this project. Could you provide `.bib`  bibliography file?

Thank you.

**Comment by tkf** [comment]
Hi, I just added a zendo badge in #430. You can get a BibTeX export at the right bottom `Export` square in https://zenodo.org/badge/latestdoi/14576985

**Comment by stevengogogo** [comment]
Thank you !
