### ISSUE TITLE
Redirect julia STDOUT to python sys.stdout?

### ISSUE THREAD

**Issue by colinfang** [JuliaPy/pyjulia#49]
Is it possible for python to capture `print` from julia? So that `STDOUT` from julia is fed to some python's `OutStream`?

**Comment by stevengj** [comment]
It should be possible to reassign `STDOUT` to a new stream type that you define to write to Python's `OutStream`.   (This won't capture stdio from C libraries, though.)

**Comment by lthurner** [comment]
I am trying to achieve this, but couldn't quite get it to work. I found the redirect_stdout function, which redirects STDOUT to a pipe. I tried to call this function from Python to get a pipe I can read on the Python side like this:

> from julia.Main import println, redirect_stdout
rd, wr = redirect_stdout()
println("foo")
println("bar")

The rd pipe now contains the two strings. I can access them with:

> rd.readline()

Which prints "bar" the first time it is called and "foo" the second time its called, so it is working in principle. However, if there is nothing left in the pipe and rd.readline() is called, the console crashes. The same happens for other functions, such as rd.readall() or rd.readlines(). I would like a solution where I can connect the pipe directly to the print statement or a logger in Python, is that possible? 

I am using Julia 0.64 and pyjulia 0.2

**Comment by tkf** [comment]
Here is an implementation to do the redirection (mostly based on IJulia's code):

https://github.com/tkf/ipyjulia_hacks/blob/f5d0e0f91da5a2bca7a987de2e634e04f88c76c4/src/ipyjulia_hacks/core/julia_api.jl#L221-L289
https://github.com/tkf/ipyjulia_hacks/blob/f5d0e0f91da5a2bca7a987de2e634e04f88c76c4/src/ipyjulia_hacks/core/julia_api.py#L155-L164
