### ISSUE TITLE
Can't print in Google Colab

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaPy/pyjulia#498]
I'm trying to use PyJulia in Google colab (colab.research.google.com), and for some reason, I can't print anything from Julia.

For example:
Cell [1] **installation**
```shell
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.7.2"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz
  julia -e 'println("Success")'
fi
```

Cell [2] **test**
```python
from julia import Julia
julia = Julia(compiled_modules=False)
from julia import Main
Main.println("Test")
```
There is no output. I also tried:
```python
Main.eval('println(stderr, "Test")')
```
and there's still no output.

Any idea what's going on?

**Comment by mkitti** [comment]
Maybe stdout has not been redirected in the expected way?

https://docs.julialang.org/en/v1/base/io-network/#Base.redirect_stdout-Tuple{Function,%20Any}

**Comment by MilesCranmer** [comment]
Hm, I'm not sure what to direct it to - redirecting to stdout and stderr doesn't seem to help.

I found this https://github.com/JuliaPy/pyjulia/blob/87c669e2729f9743fe2ab39320ec9b91c9300a96/src/julia/magic.py#L70-L78 
which looks promising maybe?

**Comment by MilesCranmer** [comment]
Yep, its a redirection problem!

I found the function `redirect_output_streams` which seems to fix this issue:

```python
from julia.tools import redirect_output_streams
redirect_output_streams()
Main.println("Test")
# > Test
```

Output:
![Screen Shot 2022-05-24 at 4 29 56 PM](https://user-images.githubusercontent.com/7593028/170126496-d7f7d56d-0cce-479e-9902-e0a371dfb2aa.png)

Thanks for the quick help @mkitti!

**Comment by mkitti** [comment]
Well wait a minute. Why is `redirect_output_streams()` not invoked automatically?

**Comment by MilesCranmer** [comment]
I can see the print statements in Jupyter, but not in Colab. So I'm assuming that it was no longer necessary for Jupyter (?) and it simply wasn't tested in colab?

It would be great to have it automatically set up. However, there's a comment in the function that indicates it kills the python process if ran in IPython, so we should be careful if we want it to automatically run.

**Comment by mkitti** [comment]
My guess is that this function does not return true:
https://github.com/JuliaPy/pyjulia/blob/87c669e2729f9743fe2ab39320ec9b91c9300a96/src/julia/magic.py#L140-L145

**Comment by MilesCranmer** [comment]
Looks fine...
![Screen Shot 2022-05-24 at 7 07 31 PM](https://user-images.githubusercontent.com/7593028/170146150-c175b231-ef3f-4283-9cef-bd94540c5f70.png)

**Comment by mkitti** [comment]
Hmm... then it must be something else here:
https://github.com/JuliaPy/pyjulia/blob/87c669e2729f9743fe2ab39320ec9b91c9300a96/src/julia/magic.py#L178-L181
