### ISSUE TITLE
'Scalar indexing is disallowed' when moving array to GPU

### ISSUE THREAD

**Issue by EmeEmu** [JuliaPy/pyjulia#528]
Hey,
I have a problem with PyJulia when moving an array to the GPU.

### The Problem
Doing the following in a Julia console raises no issue :
```julia
using CUDA: cu
cu(rand(Bool, (10,10)))
```

But with Python (+PyJulia) : 
```python
import julia
jl = julia.Julia(compiled_modules=False)
jl.eval("using CUDA: cu")
jl.eval("cu(rand(Bool, (10,10)))")
```
I get the following error : 
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    jl.eval("cu(rand(Bool, (10,10)))")
  File "/home/myname/.local/lib/python3.8/site-packages/julia/core.py", line 633, in eval
    self.check_exception("convert(PyCall.PyObject, {})".format(src))
  File "/home/myname/.local/lib/python3.8/site-packages/julia/core.py", line 609, in check_exception
    raise JuliaError(u'Exception \'{}\' occurred while calling julia code:\n{}'
julia.core.JuliaError: Exception 'Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.' occurred while calling julia code:
convert(PyCall.PyObject, cu(rand(Bool, (10,10))))
```
The important part being : `Scalar indexing is disallowed`. I don't completely understand this error, but the fact that it happens only through python is what I'm worried about. Is it an expected behavior ? Have I missed something important ?

### Attempted fixes
I tried different ways of doing the same thing, with no effect :
1. defining a variable first : `jl.eval("x = rand(Bool, (10,10))") ; jl.eval("cu(x)")`
2. different datatype : `jl.eval("x = rand(Float32, (10,10))")`
3. defining a function in a `.jl` file : 
```julia
#test.jl
using CUDA: cu
function foo()
    x = rand(Bool, (10,10))
    y = cu(x)
    return y
end
```
```python
#test.py
import julia
jl = julia.Julia(compiled_modules=False)
jl.include("test.jl")
jl.foo()
```
### Info
I running on Linux with a conda environment (python 3.8.5) (hence the `compiled_modules=False`). Julia is 1.8.5, and PyJulia is 0.6.1
I'm new to Julia and PyJulia.

I hope you will be able to help me :smiley: !

**Comment by mkitti** [comment]
Consider adding a semicolon so that it does not try to print the array.

**Comment by jimin9292** [comment]
> Consider adding a semicolon so that it does not try to print the array.

I am having a same issue - adding a semicolon inside the eval() doesn't seem to work. Could you elaborate on where exactly should I put the semicolon or suggest any other solution?

**Comment by mkitti** [comment]
Is the array printing? If so, stop it from printing. Maybe do `jl.eval("cu(rand(Bool, (10,10))); nothing")`

**Comment by jimin9292** [comment]
Just confirmed that `jl.eval("cu(rand(Bool, (10,10)));")` results in the scalar exception error but adding nothing after the semicolon `jl.eval("cu(rand(Bool, (10,10))); nothing")` doesn't invoke the error. Thank you!
