### ISSUE TITLE
Register with PyPI?

### ISSUE THREAD

**Issue by ararslan** [JuliaPy/pyjulia#58]
It would be awesome to see PyJulia registered in the [Python Package Index (PyPI)](https://pypi.python.org/pypi), be it now or some time in the future.

**Comment by PallHaraldsson** [comment]
Yes. I searched for "julia" and there are packages related (and other not related) to Julia, such as:

https://pypi.python.org/pypi/julia/0.1.1

Not sure, if that one would be outdated, as more specific (or maybe it's completely unrelated to calling between languages).

**Comment by sondree** [comment]
I agree, this would help a lot. First we should make sure it works with the standard repository binaries though (ref #57 )

**Comment by PallHaraldsson** [comment]
Isn't now a good time? pyjulia for sure working, e.g. on Windows (and Julia 0.5, that is released, great! Now I'll promote..).

Some while back on julia-users, a user of "julia" that is in PyPI was in trouble and I pointed to this. That solved it. Anyone know what do do with that or who did/maintains that? Is it an old version of pyjulia (e.g. was julia renamed?). Even further back, I guess this used same version (recursive would still be cool, should I say it works/supported..?:

http://blog.leahhanson.us/post/julia/julia-calling-python.html
