### ISSUE TITLE
Transfer to JuliaPy?

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/pyjulia#61]
cc @ViralBShah

**Comment by ViralBShah** [comment]
I have sent @tkelman an invite to be owner of JuliaPy

**Comment by tkelman** [comment]
JuliaInterop is now nearly empty which is unfortunate, but very well.

**Comment by stevengj** [comment]
Probably JuliaInterop should consider inviting packages like Rcall.jl and JavaCall.jl

**Comment by ViralBShah** [comment]
Rcall.jl is in JuliaStats, and perhaps may need to stay in there for similar reasons (to integrate with the R ecosystem) as PyCall being in JuliaPy. JavaCall should certainly go into JuliaInterop.

**Comment by tkelman** [comment]
> I can't do it because I'm not a member of JuliaInterop

I sent you an invitation some time ago. Doesn't look like you've accepted it yet.
