### ISSUE TITLE
j.call("using Clustering") broken in 0.5?

### ISSUE THREAD

**Issue by nbecker** [JuliaPy/pyjulia#62]
python 3.5.1
Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)

In [11]: j.call("using Clustering")
WARNING: call(f,args...) is deprecated, use f(args...) instead.
 in ##979#980(::Array{Any,1}, ::Function, ::String) at ./deprecated.jl:271
 in (::Base.##979#981)(::String) at ./deprecated.jl:270
 in jl_Function_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /home/nbecker/.julia/v0.5/PyCall/src/callback.jl:35
while loading no file, in expression starting on line 0
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-ac1f1c56081c> in <module>()
----> 1 j.call("using Clustering")

RuntimeError: Julia exception: MethodError("using Clustering",())

**Comment by nbecker** [comment]
It appears the current git version has a 'using' method:
j.using('DSP')

This seems to add all functions from the module to the 'j' python object

**Comment by stevengj** [comment]
`using Clustering` is not a function, so you wouldn't use `j.call` anyway.  I think you are thinking of `j.eval` to evaluate a string?   But `using` seems to be better anyway.
