### ISSUE TITLE
access julia types from python?

### ISSUE THREAD

**Issue by nbecker** [JuliaPy/pyjulia#63]
I'm trying to use the FIRFilter type, from the julia DSP module,  from python

This doesn't seem to work, I believe because
j = julia.Julia()
j.using('DSP')

adds all functions from DSP, but not types.  I conclude that by adding a print within core.py::add_module_functions, and I see lots of functions added, but not FIRFilter

see http://dspjl.readthedocs.io/en/latest/filters.html

**Comment by stevengj** [comment]
Does `j.DSP.FIRFilter` work?

**Comment by stevengj** [comment]
But I agree that `using` should add all of the module's exports, not just the functions.

**Comment by nbecker** [comment]
As an experiment, I tried allowing Types to be added as well as functions,
but it doesn't seem to work

j.using('DSP')
 j.FIRFilter(np.linspace(1,10), r)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-88-7bc878ee9c69> in <module>()
----> 1 j.FIRFilter(np.linspace(1,10), r)

TypeError: 'PyCall.jlwrap' object is not callable

In [89]: j.FIRFilter
Out[90]:
<PyCall.jlwrap DSP.Filters.FIRFilter{Tk<:DSP.Filters.FIRKernel}>

In [91]:

So the type "FIRFilter" got added, but it doesn't seem to be usable, since
I can't seem to call it's constructor

**Comment by stevengj** [comment]
That's probably something that needs to be fixed in PyCall; right now it does not translate Julia types into callable objects.   Since for a while now any Julia object can potentially be callable, PyCall should add a call method for `jlwrap` of any type.

**Comment by Keno** [comment]
Now fixed.
