### ISSUE TITLE
Error while calling julia from python

### ISSUE THREAD

**Issue by karanaggarwal1994** [JuliaPy/pyjulia#70]
`    jl.sind(90) AttributeError: 'Julia' object has no attribute 'sin`

**Comment by kmsquire** [comment]
Hi @karanaggarwal1994, can you provide the code you ran, so that others can reproduce?

**Comment by karanaggarwal1994** [comment]
```
from julia import Julia 

def harris_jul(frame, lib_func):
	jl = Julia()
	jl.sind(90)
	return frame
```

This is .py file

**Comment by kmsquire** [comment]
It seems that defining `jl = Julia()` inside the function is the source of the problem, although I'm not sure exactly why.  If you instead either define `jl = Julia()` as a global variable, or pass it in as a parameter to the function, everything works fine:

```python
from julia import Julia

jl = Julia()

def harris_jul(frame, lib_func):
    print jl.sind(90)
    return frame
```

In Julia and most other modern programming languages, globals are discouraged, but in this case, it could be argued that this is a singleton instance that plays a similar role to a module.  At any rate, treating it like a singleton, you could do something a little fancier like

```python
from julia import Julia

def julia_singleton():
    if not hasattr(julia_singleton, "__instance"):
        julia_singleton.__instance = Julia()
    return julia_singleton.__instance

def harris_jul(frame, lib_func):
    jl = julia_singleton()
    print jl.sind(90)
    return frame
```

which seems to work just fine, and is arguably better than a simple global variable.

**Comment by karanaggarwal1994** [comment]
This is working for me.
Thank You

**Comment by karanaggarwal1994** [comment]
```
def julia_singleton():
	if not hasattr(julia_singleton, "__instance"):
		julia_singleton.__instance = Julia()
	return julia_singleton.__instance

def harris_jul(frame, lib_func):
	jl = julia_singleton()
	f=jl.eval("""
		function f(x::Float64)
			return 2*x
			end
		""")
	x=f(4.4)
	print(x)
return
```
WARNING: Method definition f(Float64) in module Main at none:3 overwritten at none:3.
8.8

Why warning is coming along with result?

**Comment by stevengj** [comment]
Because every time you call `harris_jul` it redefines `f`; you should normally define (named) Julia functions only once for given argument types.  Alternatively, if you want an anonymous function, you can do `jl.eval("x -> 2*x")`.

PS. Julia is not Cython; there is no performance advantage to declaring argument types like `x::Float64`.

**Comment by stevengj** [comment]
By the way, this is one of those cases where you should just use a global for `jl = Julia()`, I think.

**Comment by karanaggarwal1994** [comment]
Is there any check condition that we can put to check if a Julia function with same signature exists then skip it else make it.
