### ISSUE TITLE
`addprocs` leads to segfault

### ISSUE THREAD

**Issue by ihnorton** [JuliaPy/pyjulia#71]
```
import julia
j = julia.Julia(jl_runtime_path="/Users/inorton/git/julia/usr/bin/julia",  
 jl_init_path="/Users/inorton/git/julia/usr/bin")
j.addprocs(1)
#segfault
```

(segfault stack [here](https://gist.github.com/ihnorton/63dabfa2316d2e29eb0941eaa70ab7ce))

Based on the stack trace, I thought there might be some issue with task switching because of ctypes (libffi) stack. However, running the following (equivalent?) code does not segfault:

```
JLPATH="/Users/inorton/git/julia"
import ctypes
jl = ctypes.PyDLL(JLPATH+"/usr/lib/libjulia.dylib", ctypes.RTLD_GLOBAL)
jl.jl_init(JLPATH+"/usr/bin/")
jl.jl_eval_string(""" addprocs(1) """)
jl.jl_eval_string(""" println(nprocs()) """)
# 2
```

Tested with 0.4.6, 0.5, and a several-day-old trunk build.
(cross-ref: https://discourse.julialang.org/t/julia-call-from-python3-running-in-single-core/508)

**Comment by yuyichao** [comment]
This is caused by the stack limit being wrong. No julia runtime code should be executed with a higher stack address than the one when `jl_init` is called.

**Comment by yuyichao** [comment]
This should be closed.

**Comment by CorbinFoucart** [comment]
Has this issue been fixed, or is the way to handle this to use the workaround listed by @ihnorton? If it has been fixed, what is the correct way to pull the changes? I would like to avoid the seg-fault in the most sensible way possible.

**Comment by yuyichao** [comment]
See the linked pull request.
