### ISSUE TITLE
Happy to transfer ownership of pypi/julia

### ISSUE THREAD

**Issue by Carreau** [JuliaPy/pyjulia#74]
Hey there, 

Just want to say that I am of of the owner of the [`julia`](https://pypi.python.org/pypi/julia) name on the Python Packaging Index (aka PyPI) with @stevengj , if any of the owner here want to be added as a package maintainer or owner, I'll be happy to do it. 

If you just need me to build the package and upload it I can do that as well. 
Also while I'm at it, It woudl be interesting to put a dummy repo in https://github.com/JuliaInterop (PyCall.jl) that redirect to this organisation)

**Comment by stevengj** [comment]
That would be great!   If you could hep build the package and upload, that would be much appreciated.

Is there some way to automate building and uploading the pypi package whenever we tag a new version on github?

**Comment by Carreau** [comment]
> That would be great, I had forgotten I was an owner of this! If you could help build the package and upload, that would be much appreciated.

Just ping me when you want a release I can take care of that.

> Is there some way to automate building and uploading the pypi package whenever we tag a new version on github?

Well yes and no. IFAIU one of the "owner" have to give their credential and encrypt it in Travis-CI env variable to do so (or we can create  a "Fake" user on PyPI), then with the right travis configuration it should be possible to do that. 

I'll investigate.

**Comment by stevengj** [comment]
@Keno, any thoughts on this?

**Comment by tkf** [comment]
@stevengj I've never used it, but I just found release-bot https://github.com/user-cont/release-bot developed by Red Hat.  Not sure where the bot should be run though.  (Maybe possible to run it on Travis via OpenShift/Docker?)

**Comment by stevengj** [comment]
Added @tkf as a maintainer.   I think this issue can be closed; we can add additional people as needed.
