### ISSUE TITLE
Pointing to a different julia binary

### ISSUE THREAD

**Issue by CorbinFoucart** [JuliaPy/pyjulia#75]
I work with pyjulia on a cluster, where I work in a python virtualenv. In the past, I have successfully launched pyjulia from python with:

`julia = Julia(jl_runtime_path=juliaBinPathB, debug=False)`

Now I would like to point to a different julia binary (I don't have write access to juliaBinPathA, so if there's a bug fix which I would like to have, I need to point to another julia binary, juliaBinPathB, which I have downloaded myself).

Calling 
`julia = Julia(jl_runtime_path=juliaBinPathA, debug=True)`
produces the seg fault below. What can I do to change the working binary without such an issue?

**Comment by CorbinFoucart** [comment]
After digging some more, it seems that the error is coming from the line

` println(Libdl.dlpath(string("lib",Base.julia_exename())))`

which indeed does throw a segfault if I do:
` ./juliaBinPathB`
`>println(Libdl.dlpath(string("lib",Base.julia_exename())))`

`signal (11): Segmentation fault
while loading no file, in expression starting on line 0
_ZN4llvm2cl19generic_parser_base10findOptionEPKc at /home/foucartc/julia-3c9d75391c/bin/../lib/julia/libLLVM-3.7.1.so (unknown line)
unknown function (ip: 0x7fda5f6593b6)
_ZN4llvm12PassRegistry12registerPassERKNS_8PassInfoEb at /home/foucartc/julia-3c9d75391c/bin/../lib/julia/libLLVM-3.7.1.so (unknown line)
RegisterPass at /home/centos/buildbot/slave/package_tarball64/build/usr/include/llvm/PassSupport.h:127 [inlined]
__static_initialization_and_destruction_0 at /home/centos/buildbot/slave/package_tarball64/build/src/llvm-simdloop.cpp:193 [inlined]
_GLOBAL__sub_I_llvm_simdloop.cpp at /home/centos/buildbot/slave/package_tarball64/build/src/llvm-simdloop.cpp:202
unknown function (ip: 0x3f0d80e64e)
unknown function (ip: 0x3f0d812e04)
unknown function (ip: 0x3f0d80e265)
unknown function (ip: 0x3f0d8125a9)
unknown function (ip: 0x3f0e400f65)
unknown function (ip: 0x3f0d80e265)
unknown function (ip: 0x3f0e40129b)
dlopen at /lib64/libdl.so.2 (unknown line)
jl_load_dynamic_library_ at /home/centos/buildbot/slave/package_tarball64/build/src/dlload.c:195
dlopen at ./libdl.jl:90
dlpath at ./libdl.jl:153
unknown function (ip: 0x7fd839c6f502)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:66
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7fda561874df)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7fd839c646c6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7fd839c5df2f)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 1722702 (Pool: 1721803; Big: 899); GC: 0
Segmentation fault
`

**Comment by yuyichao** [comment]
Please use multiline quote.

**Comment by CorbinFoucart** [comment]
Ok, fixed.

**Comment by yuyichao** [comment]
What are the two paths?

**Comment by CorbinFoucart** [comment]
JuliaBinPathA:
`/share/apps/julia/julia-3c9d75391c/bin/julia`

JuliaBinPathB:
`/home/foucartc/julia-3c9d75391c/bin/julia`

**Comment by CorbinFoucart** [comment]
When I execute the same line with ./JuliaBinPathA:

```
>println(Libdl.dlpath(string("lib",Base.julia_exename())))
/share/apps/julia/julia-3c9d75391c/bin/../lib/libjulia.so.0.5
```

**Comment by yuyichao** [comment]
Is `/share/apps/julia/julia-3c9d75391c` in any of the environment variables?

**Comment by CorbinFoucart** [comment]
They are here:
```
MANPATH=/share/apps/Python-2.7.11/share/man:/share/apps/gcc-6.1.0/share/man::/share/apps/netcdf-4.1.1/gfortran/share/man:/share/apps/ncarg/man:/usr/share/pvm3/man
PDSHROOT=/opt/pdsh
SSH_AGENT_PID=31146
BIOROLL=/opt/bio
HOSTNAME=mseas.mit.edu
PVM_RSH=/usr/bin/ssh
MATLABPATH=:/software/Matlab/SeaWater:/software/Matlab/SmithSand:/software/Matlab/satools
TERM=xterm-256color
SHELL=/bin/bash
SPARSROOT=/share/apps/SPARSKIT2
HISTSIZE=1000
PETSC_ARCH=arch-linux2-cxx-opt
CONDOR_IDS=407.407
HMMER_DB=/home/foucartc/bio/hmmer/db
SSH_CLIENT=18.38.7.4 37398 22
SGE_CELL=default
SGE_ARCH=linux-x64
MPICH_PROCESS_GROUP=no
QTDIR=/usr/lib64/qt-3.3
OLDPWD=/home/foucartc/julia-3c9d75391c/bin
QTINC=/usr/lib64/qt-3.3/include
ESMOND_ROOT=/opt/esmond
ROCKSROOT=/opt/rocks/share/devel
SSH_TTY=/dev/pts/7
ANT_HOME=/opt/rocks
USER=foucartc
LD_LIBRARY_PATH=/share/apps/Python-2.7.11/lib:/share/apps/gcc-6.1.0/lib64:/share/apps/gcc-6.1.0/lib:/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib:/share/apps/acml/acml4.2.0/pathscale64/lib
LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lz=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.bz=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.rar=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
ROCKS_ROOT=/opt/rocks
SSH_AUTH_SOCK=/tmp/ssh-uWOEP31145/agent.31145
PVM_ROOT=/usr/share/pvm3
ESMOND_CONF=/opt/esmond/esmond.conf
VIRTUAL_ENV=/home/foucartc/venvJul2
PVM_ARCH=LINUXX86_64
NETCDF_ROOT=/share/apps/netcdf-4.1.1/gfortran
MAVEN_HOME=/opt/maven
MAIL=/var/spool/mail/foucartc
PATH=/home/foucartc/venvJul2/bin:/share/apps/Python-2.7.11/bin:/share/apps/gcc-6.1.0/bin:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/opt/perfsonar_ps/toolkit/scripts:/usr/dbxml-2.3.11/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bio/ncbi/bin:/opt/bio/mpiblast/bin:/opt/bio/EMBOSS/bin:/opt/bio/clustalw/bin:/opt/bio/tcoffee/bin:/opt/bio/hmmer/bin:/opt/bio/phylip/exe:/opt/bio/mrbayes:/opt/bio/fasta:/opt/bio/glimmer/bin:/opt/bio/glimmer/scripts:/opt/bio/gromacs/bin:/opt/bio/gmap/bin:/opt/bio/tigr/bin:/opt/bio/autodocksuite/bin:/opt/bio/wgs/bin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/maven/bin:/opt/pdsh/bin:/usr/share/pvm3/bin/LINUXX86_64:/opt/rocks/bin:/opt/rocks/sbin:/opt/condor/bin:/opt/condor/sbin:/opt/gridengine/bin/linux-x64:/usr/local/bin:/home/foucartc/bin:/share/apps/pathscale/bin:/share/apps/x86_open64-4.2.5.1/bin:/share/apps/matlab/bin:/share/apps/netcdf-4.1.1/gfortran/bin:/share/apps/ncarg/bin:/share/apps/ncar_hdf/bin:/usr/share/pvm3/lib/LINUXX86_64:/usr/share/pvm3/bin/LINUXX86_64:/share/apps/hydrobase/bin:/share/apps/TotalView/toolworks/totalview.8.6.2-2/bin
BEAMS_NOTES_IMG=/home/foucartc/pyHDG/branches/MMSDebug/test/results/beams_debug/notes/figures
CONDOR_CONFIG=/opt/condor/etc/condor_config
PWD=/home/foucartc/julHDG/branches/MMSDebug
NCARG_ROOT=/share/apps/ncarg
_LMFILES_=/usr/share/Modules/modulefiles/rocks-openmpi
JAVA_HOME=/usr/java/latest
DJANGO_SETTINGS_MODULE=esmond.settings
HB2_ROOT=/share/apps/hydrobase
SGE_EXECD_PORT=537
LANG=en_US.UTF-8
SGE_QMASTER_PORT=536
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
SGE_ROOT=/opt/gridengine
CONDOR_ROOT=/opt/condor
LOADEDMODULES=rocks-openmpi
BLASTDB=/home/foucartc/bio/ncbi/db
PS1=(venvJul2) \h(\W)% 
ACML_ROOT=/share/apps/acml/acml4.2.0/pathscale64/lib
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
HISTCONTROL=ignoredups
GCC_ROOT=/share/apps/gcc-6.1.0
SHLVL=1
HOME=/home/foucartc
ROLLSROOT=/opt/rocks/share/devel/src/roll
MPIHOME=/opt/openmpi
LOGNAME=foucartc
QTLIB=/usr/lib64/qt-3.3/lib
CVS_RSH=ssh
SSH_CONNECTION=18.38.7.4 37398 18.38.0.138 22
MODULESHOME=/usr/share/Modules
LESSOPEN=||/usr/bin/lesspipe.sh %s
BLASTMAT=/opt/bio/ncbi/data
PETSC_DIR=/share/apps/petsc-3.6.2
OMPI_MCA_btl=self,sm,tcp
G_BROKEN_FILENAMES=1
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/share/apps/julia/julia-3c9d75391c/bin/julia
OPENBLAS_MAIN_FREE=1
```

so 
```
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/share/apps/julia/julia-3c9d75391c/bin/julia
```

**Comment by CorbinFoucart** [comment]
Is it safe to try modifying the BASH_FUNC_module variable to the new path?

**Comment by yuyichao** [comment]
It's not in that variable.

**Comment by stevengj** [comment]
Can't you just set your `PATH` variable so that the new `julia` comes first in your path, and set `LD_LIBRARY_PATH` so that the runtime linker knows where to find the new Julia's shared libraries?

**Comment by tkf** [comment]
I'm closing it since this issue is old.  Please reopen if you still have the issue.
