### ISSUE TITLE
Build failure with julia 0.5.0

### ISSUE THREAD

**Issue by bondhugula** [JuliaPy/pyjulia#76]
Version 0.5.0 (2016-09-19 18:14 UTC)

julia> Pkg.add("ParallelAccelerator")
;
INFO: Installing CompilerTools v0.2.0
INFO: Installing DataStructures v0.4.6
INFO: Installing DocOpt v0.2.0
INFO: Installing ParallelAccelerator v0.2.1
INFO: Building ParallelAccelerator
ParallelAccelerator: build.jl begin.
ParallelAccelerator: Building j2c-array shared library
Using icpc to build ParallelAccelerator array runtime.
In file included from /usr/include/c++/6.2.1/set(60),
                 from include/j2c-array.h(41),
                 from j2c-array.cpp(26):
/usr/include/c++/6.2.1/bits/stl_tree.h(1437): error: identifier "_Compare" is undefined
  	     && is_nothrow_move_assignable<_Compare>::value)
  	                                   ^

In file included from /usr/include/c++/6.2.1/set(60),
                 from include/j2c-array.h(41),
                 from j2c-array.cpp(26):
/usr/include/c++/6.2.1/bits/stl_tree.h(1778): error: identifier "_Compare" is undefined
      _GLIBCXX_NOEXCEPT_IF(__is_nothrow_swappable<_Compare>::value)
      ^

compilation aborted for j2c-array.cpp (code 2)
================================================[ ERROR: ParallelAccelerator ]================================================

LoadError: failed process: Process(`./build.sh '' /opt/intel/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/mpirt/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/tools/intel64/perfsys:/opt/intel/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/mkl/lib/intel64:/opt/intel/composer_xe_2015.3.187/tbb/lib/intel64/gcc4.1:/opt/intel/composer_xe_2015.3.187/debugger/libipt/intel64/lib:/usr/lib64/openmpi/lib:/opt/intel/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/mpirt/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/lib/intel64:/opt/intel/composer_xe_2015.3.187/ipp/tools/intel64/perfsys:/opt/intel/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/composer_xe_2015.3.187/mkl/lib/intel64:/opt/intel/composer_xe_2015.3.187/tbb/lib/intel64/gcc4.1:/opt/intel/composer_xe_2015.3.187/debugger/libipt/intel64/lib:/usr/lib64/openmpi/lib:`, ProcessExited(2)) [2]
while loading /home/user/.julia/v0.5/ParallelAccelerator/deps/build.jl, in expression starting on line 94

==============================================================================================================================

=======================================================[ BUILD ERRORS ]=======================================================

WARNING: ParallelAccelerator had build errors.

 - packages with build errors remain installed in /home/user/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("ParallelAccelerator")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================
INFO: Package database updated

**Comment by yuyichao** [comment]
This does not look like a build error from `pyjulia`. Please report to the correct package.

Please also quote all the code and output.

**Comment by bondhugula** [comment]
I was under the impression that I was on ParallelAccelerator's GitHub website; didn't realise it was pyjulia's!
