### ISSUE TITLE
Required Version of libstdc++.so.6

### ISSUE THREAD

**Issue by bcriger** [JuliaPy/pyjulia#78]
I'm trying to run the basic example code from the README:

    import julia
    j = julia.Julia()

I get the following traceback:

    ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-2-f420be51b3fc> in <module>()
    ----> 1 j = julia.Julia()
    
    /home/dcriger/.local/lib/python2.7/site-packages/julia-0.1.1-py2.7.egg/julia/core.pyc in __init__(self, init_julia, jl_runtime_path, jl_init_path, debug)
        275             if not os.path.exists(libjulia_path):
        276                 raise JuliaError("Julia library (\"libjulia\") not found! {}".format(libjulia_path))
    --> 277             self.api = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
        278             if not jl_init_path:
        279                 if jl_runtime_path:
    
    /home/dcriger/anaconda2/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
        360 
        361         if handle is None:
    --> 362             self._handle = _dlopen(self._name, mode)
        363         else:
        364             self._handle = handle
    
    OSError: /home/dcriger/anaconda2/lib/python2.7/site-packages/matplotlib/../../../libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1)

I have multiple copies of `libstdc++.so.6` on my computer. One of them is in `~/anaconda2/lib/`, where `pyjulia` finds it. running `strings` on this file, I can see that it contains `GLIBCXX_3.4` and `GLIBCXX_3.4.1` up to `GLIBCXX_3.4.21`, but not `GLIBCXX_3.4.22`. There is another `libstdc++.so.6` in `/usr/lib/x86_64-linux-gnu/` which does contain `GLIBCXX_3.4.22`.

Should I:
 - try to change a path variable such that `pyjulia` can find the newer file,
 - update Anaconda somehow to place the newer file in the path that `pyjulia` is already searching, or
 - do something cleverer than either of these options?

**Comment by tkelman** [comment]
Try moving the old anaconda-bundled version out of the way. If your system copy is newer, it should get picked up and work fine.

**Comment by nicklafarge** [comment]
I am having this issue as well. Were you able to solve it?

**Comment by tkf** [comment]
I'm closing it since this issue is old.  Please reopen if you still have the issue.

See also #223.
