### ISSUE TITLE
@parallel different behaviour in prompt and script

### ISSUE THREAD

**Issue by karanaggarwal1994** [JuliaPy/pyjulia#85]
```
@parallel for c3=1:c_cols-1
end
```
Works in julia prompt but does't work when used in script.

**Comment by stevengj** [comment]
What do you mean by "works" and "doesn't work"?   Also, this is Julia code, why are you reporting it at pyjulia?

**Comment by tkf** [comment]
I'm closing it since this issue is old.  Please reopen if you still have the issue.
