### ISSUE TITLE
ERROR: could not open file boot.jl

### ISSUE THREAD

**Issue by stustd** [JuliaPy/pyjulia#86]
pyjulia tests (python -m unittest discover) pass on Julia 0.5.0. With Julia 0.6dev however I receive:

JULIA_HOME = /home/opt/inst/julia/0.6/dev/openblas/bin,  libjulia_path = /home/opt/inst/julia/0.6/dev/openblas/bin/../lib/libjulia.so.0.6
calling jl_init(b'/home/opt/inst/julia/0.6/dev/openblas/bin')
**ERROR: could not open file boot.jl**

Julia 0.6dev REPL works fine. Anyone some idea? Thanks!

**Comment by tkf** [comment]
I'm closing it since this issue is old.  Newer versions of PyJulia/Julia/Python may solve it.  Please reopen if you still have the issue.
