### ISSUE TITLE
error could not open file boot.jl on v0.6

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaPy/pyjulia#94]
It would be a miracle if this were the only problem with v0.6, but for the time being, one gets
```
j = julia.Julia()
>>> ERROR: could not open file boot.jl
```
This happens on the call to `jl_init` [here](https://github.com/JuliaPy/pyjulia/blob/master/julia/core.py#L292).  The Julia documentation on `jl_init` says that if it is passed a `NULL` it will try to automatically infer the install directory (which I'd assume it'd do be reading the `$JULIA_HOME` environment variable).  

I tried to see if I could fix it by setting `jl_init_path` to `$JULIA_HOME` (which recall is actually, for example `/opt/julia/bin` not just `/opt/julia`) and got the same error.  I also tried setting it to `$JULIA_HOME/../` and got the same error.  I don't even know where it's *supposed* to point, the Julia documentation just says "the Julia install directory" which is of course ambiguous.

I suppose one fix to this would be to have python figure out the install directory by looking at `$JULIA_HOME` once we figure out where `jl_init_path` is supposed to be, although it would be a far more elegant solution to figure out why Julia can no longer find `boot.jl` in v0.6.

**Comment by Keno** [comment]
Should be fixed by #110. Please open a new issue if not.
